# Generated by Django 5.0.7 on 2024-08-10 14:43

import handlers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[handlers.validators.ban_words_validator], verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, validators=[handlers.validators.ban_words_validator], verbose_name='Никнейм'),
        ),
    ]
