# Generated by Django 5.0.7 on 2024-09-17 18:40

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_profile_avatars', validators=[users.validators.mime_type_validator], verbose_name='Изображение профиля'),
        ),
    ]
