# Generated by Django 5.0.7 on 2024-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_dislike_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waters', to='blog.post', verbose_name='Пост'),
        ),
    ]
