# Generated by Django 5.0.7 on 2024-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, to='courses.lessonmaterial', verbose_name='Материалы к уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='questions',
            field=models.ManyToManyField(blank=True, to='courses.lessonquestion', verbose_name='Вопросы к уроку'),
        ),
    ]
