# Generated by Django 5.0.7 on 2024-08-07 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmaterial',
            name='file',
            field=models.FileField(upload_to='lesson_materials/', validators=[django.core.validators.FileExtensionValidator(['zip', 'jpg', 'pdf'])], verbose_name='Файл'),
        ),
    ]
