# Generated by Django 5.0.7 on 2024-08-10 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='theme',
            name='lessons',
            field=models.ManyToManyField(to='courses.lesson', verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='course',
            name='themes',
            field=models.ManyToManyField(to='courses.theme', verbose_name='Разделы курса'),
        ),
    ]
