# Generated by Django 5.0.7 on 2024-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование урока'),
        ),
    ]
