# Generated by Django 5.0.7 on 2024-08-10 08:58

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(validators=[courses.validators.ban_words_validator], verbose_name='Текст отзыва'),
        ),
    ]
