# Generated by Django 5.0.7 on 2024-08-10 12:44

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Уровни скилла и опыта',
            },
        ),
        migrations.CreateModel(
            name='QuestionTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Наименование вопроса')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ на вопрос')),
                ('categories', models.ManyToManyField(to='training.category', verbose_name='Категории')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.grade', verbose_name='Уровень скилла и опыта')),
            ],
            options={
                'verbose_name': 'Вопросы тренажера',
            },
        ),
    ]
