# Generated by Django 5.0.7 on 2024-08-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Уровень скилла и опыта', 'verbose_name_plural': 'Уровни скилла и опыта'},
        ),
        migrations.AlterModelOptions(
            name='questiontraining',
            options={'verbose_name': 'Вопрос тренажера', 'verbose_name_plural': 'Вопросы тренажера'},
        ),
    ]
